name: CI

on:
  workflow_dispatch:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  clang-format-check:
    name: Clang-format formatting check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check.
      uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: '10'
  
  black-check:
    name: Black formatting check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run black style check
        uses: psf/black@stable
        with:
          version: "23.7.0"

  industrial_ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ROS_DISTRO: [noetic]
        ROS_REPO: [testing, main]
    env: 
      ROS_DISTRO: ${{ matrix.ROS_DISTRO }}
      ROS_REPO: ${{ matrix.ROS_REPO }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: Source tests
        uses: 'ros-industrial/industrial_ci@master'
        env:
          UPSTREAM_WORKSPACE: 'github:LeoRover/leo_common#master'
          CLANG_TIDY: true
          CATKIN_LINT: true
          PYLINT_CHECK: true
          PYLINT_ARGS: '--rcfile=src/leo_robot/.pylintrc'
          PYLINT_EXCLUDE: 'setup.py'
